from django.urls import path
from . import views
from .views import (
    EventCategoryListView,
    EventCategoryCreateView,
    EventCategoryUpdateView,
    EventCategoryDeleteView,
    EventCreateView,
    EventListView,
    EventUpdateView,
    EventDetailView,
    EventDeleteView,
   # AddEventMemberCreateView,
   # JoinEventListView,
   # RemoveEventMemberDeleteView,
    AbsenceUserList,
    CompleteEventList,
    EventUserWishListView,
    AddEventUserWishListCreateView,
    RemoveEventUserWishDeleteView,
    UpdateEventStatusView,
    CompleteEventList,
    CreateUserMark,
    UserMarkList,
    search_event_category,
    search_event,
    create_event,
    profile,
    feedback_view,
    feedback_success,
    save_absence,
    mark_attendance,
)

urlpatterns = [
    path('feedback/', feedback_view, name='feedback'),
    path('feedback/success/', feedback_success, name='feedback_success'),
    path("save-absence/", save_absence, name="save-absence"),
  path('mark-attendance/<int:event_id>/', views.mark_attendance, name='mark-attendance'),
path('attendance/', views.attendance_list, name='attendance_list'),
    path('category-list/', EventCategoryListView.as_view(), name='event-category-list'),
    path('create-category/', EventCategoryCreateView.as_view(), name='create-event-category'),
    path('category/<int:pk>/edit/', EventCategoryUpdateView.as_view(), name='edit-event-category'),
    path('category/<int:pk>/delete/', EventCategoryDeleteView.as_view(), name='delete-event-category'),
    path('event-create/', EventCreateView.as_view(), name='event-create'),
    path('event-list/', EventListView.as_view(), name='event-list'),
    path('event/<int:pk>/edit/', EventUpdateView.as_view(), name='event-edit'),
    path('detail/<int:pk>', EventDetailView.as_view(), name='event-detail'),
    path('delete/<int:pk>', EventDeleteView.as_view(), name='event-delete'),
    path('register/', views.register_event, name='register-event'),
    path('registration-success/', views.registration_success, name='registration_success'),
    path('event/<int:event_id>/teams/', views.event_teams, name='event-teams'),
    path('events/detail/<int:pk>', EventDetailView.as_view(), name='event-detail'),


    path('my-events/', views.my_events, name='my-events'),
    path('cancel-registration/', views.cancel_registration, name='cancel-registration'),
    path('event-wish-list/', EventUserWishListView.as_view(), name='event-wish-list'),
    path('add-event-wish-user/', AddEventUserWishListCreateView.as_view(), name='add-event-wish-user'),
    path('event-user-wish/<int:pk>/remove/', RemoveEventUserWishDeleteView.as_view(), name='remove-event-user-wish'),
    path('update-status/<int:pk>/event/', UpdateEventStatusView.as_view(), name='update-event-status'),
    path('complete-event/', CompleteEventList.as_view(), name='complete-event'),
    path("absence-user/", AbsenceUserList.as_view(), name="absence-user"),

    path('complete-event-user/', CompleteEventList.as_view(), name='complete-event-user'),
    path('create-user-mark/', CreateUserMark.as_view(), name='create-user-mark'),
    path('user-mark/', UserMarkList.as_view(), name='user-mark'),
    path('search_category/', search_event_category, name='search-event-category'),
    path('search_event/', search_event, name='search-event'),
    path('create/', create_event, name='create'),
    path('profile/', profile, name='profile'),
]



