# Generated by Django 4.2 on 2025-06-11 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_course_repport_remove_cours_prof_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repport',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='repport',
            name='student',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Repport',
        ),
    ]
