# Generated by Django 5.1.7 on 2025-03-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_absenceuser_id_alter_event_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_team_size',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='event',
            name='min_team_size',
            field=models.IntegerField(default=1),
        ),
    ]
