# Generated by Django 5.1.7 on 2025-03-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_max_team_size_event_min_team_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='payment_proof',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='status',
        ),
        migrations.AddField(
            model_name='registration',
            name='team_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='team_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
