# Generated by Django 5.1.7 on 2025-03-17 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_registration_payment_proof_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='college_name',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='email',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='name',
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('college_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=15)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='events.registration')),
            ],
        ),
    ]
