# Generated by Django 5.1.7 on 2025-03-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_registration_college_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('registered', 'Registered'), ('canceled', 'Canceled')], default='registered', max_length=20),
        ),
    ]
