# Generated by Django 5.1.7 on 2025-03-23 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_feedback'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventuserwishlist',
            unique_together={('event',)},
        ),
        migrations.RemoveField(
            model_name='eventuserwishlist',
            name='user',
        ),
    ]
