# Generated by Django 5.1.7 on 2025-03-28 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_eventuserwishlist_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='user',
        ),
        migrations.AddField(
            model_name='attendance',
            name='contact_number',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AddField(
            model_name='attendance',
            name='email',
            field=models.EmailField(default='unknown@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='attendance',
            name='member_name',
            field=models.CharField(default='Unknown Member', max_length=255),
        ),
        migrations.AddField(
            model_name='attendance',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.registration'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='team_name',
            field=models.CharField(default='Unknown Team', max_length=255),
        ),
        migrations.AddField(
            model_name='attendance',
            name='team_size',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='attendance',
            name='upi_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], default='absent', max_length=10),
        ),
        migrations.AlterField(
            model_name='registration',
            name='team_name',
            field=models.CharField(blank=True, default='No Team', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='team_size',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='upi_id',
            field=models.CharField(blank=True, default='Unknown', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='college_name',
            field=models.CharField(default='Unknown College', max_length=255),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='contact_number',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='name',
            field=models.CharField(default='Unknown Member', max_length=255),
        ),
    ]
