# Generated by Django 2.2.28 on 2025-06-07 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_registration_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='email',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='member_name',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='team_name',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='team_size',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='upi_id',
        ),
        migrations.AddField(
            model_name='attendance',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.TeamMember'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Team'),
        ),
    ]
